// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6Q1txMpJv7No5qcdYBaSThDUAmfq1s0k',
    appId: '1:35319749462:web:48f1ec0877027728d8d4f7',
    messagingSenderId: '35319749462',
    projectId: 'digipolicy-5fc2e',
    authDomain: 'digipolicy-5fc2e.firebaseapp.com',
    storageBucket: 'digipolicy-5fc2e.firebasestorage.app',
    measurementId: 'G-CD16B8EJP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa6RnbcocE7UBBULSXr9BBt8oJ74-ZhLg',
    appId: '1:35319749462:android:59088e246887abadd8d4f7',
    messagingSenderId: '35319749462',
    projectId: 'digipolicy-5fc2e',
    storageBucket: 'digipolicy-5fc2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVX6UHnYIUUPtxynNiubqJF5GEK0im0Z8',
    appId: '1:35319749462:ios:37741d6123f87dadd8d4f7',
    messagingSenderId: '35319749462',
    projectId: 'digipolicy-5fc2e',
    storageBucket: 'digipolicy-5fc2e.firebasestorage.app',
    iosBundleId: 'com.example.turfnpark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVX6UHnYIUUPtxynNiubqJF5GEK0im0Z8',
    appId: '1:35319749462:ios:37741d6123f87dadd8d4f7',
    messagingSenderId: '35319749462',
    projectId: 'digipolicy-5fc2e',
    storageBucket: 'digipolicy-5fc2e.firebasestorage.app',
    iosBundleId: 'com.example.turfnpark',
  );
}
